package schema

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
)

// FakeVendorHash is the placeholder written for a SIG's vendorHash before
// its real value has been resolved via nixtool.ResolveVendorHash.
const FakeVendorHash = "sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="

const hashesComment = "Generated by 'make generate-hashes'. Do not edit manually. vendorHash fields require manual update via nix build (use fake hash to get correct value)."

// CoreHash is the hashes.json value for one Kubernetes minor's core source.
type CoreHash struct {
	Version string `json:"version"`
	SrcHash string `json:"srcHash"`
	Commit  string `json:"commit"`
}

// SigHash is the hashes.json value for one SIG at one Kubernetes minor.
// Field order (version, commit, vendorHash, srcHash) intentionally differs
// from CoreHash's (version, srcHash, commit) — matches the existing file.
type SigHash struct {
	Version    string `json:"version"`
	Commit     string `json:"commit"`
	VendorHash string `json:"vendorHash"`
	SrcHash    string `json:"srcHash"`
}

// HashesFile is the schema of hashes.json.
type HashesFile struct {
	Kubernetes map[string]CoreHash           // keyed by k8s minor
	Sigs       map[string]map[string]SigHash // sig name -> k8s minor -> SigHash
}

// LoadHashes reads and parses hashes.json from path.
func LoadHashes(path string) (*HashesFile, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var raw struct {
		Kubernetes map[string]CoreHash           `json:"kubernetes"`
		Sigs       map[string]map[string]SigHash `json:"sigs"`
	}
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, fmt.Errorf("schema: parsing %s: %w", path, err)
	}
	if raw.Kubernetes == nil {
		raw.Kubernetes = map[string]CoreHash{}
	}
	if raw.Sigs == nil {
		raw.Sigs = map[string]map[string]SigHash{}
	}
	for _, sig := range Sigs {
		if raw.Sigs[sig] == nil {
			raw.Sigs[sig] = map[string]SigHash{}
		}
	}
	return &HashesFile{Kubernetes: raw.Kubernetes, Sigs: raw.Sigs}, nil
}

// SaveHashes writes h to path as indented JSON, with the kubernetes and
// per-sig minor keys ordered per minors (typically VersionsFile.Supported)
// and the top-level sigs keys ordered per Sigs, rather than the alphabetical
// order Go's map marshaling would otherwise produce.
func SaveHashes(path string, h *HashesFile, minors []string) error {
	kubernetesJSON, err := marshalOrderedObject(minors, func(k string) (any, error) {
		entry, ok := h.Kubernetes[k]
		if !ok {
			return nil, fmt.Errorf("schema: hashes.json missing kubernetes entry for minor %q", k)
		}
		return entry, nil
	})
	if err != nil {
		return err
	}

	sigsJSON, err := marshalOrderedObject(Sigs, func(sig string) (any, error) {
		perMinor := h.Sigs[sig]
		minorJSON, err := marshalOrderedObject(minors, func(m string) (any, error) {
			entry, ok := perMinor[m]
			if !ok {
				return nil, fmt.Errorf("schema: hashes.json missing %s entry for minor %q", sig, m)
			}
			return entry, nil
		})
		if err != nil {
			return nil, err
		}
		return json.RawMessage(minorJSON), nil
	})
	if err != nil {
		return err
	}

	commentJSON, err := json.Marshal(hashesComment)
	if err != nil {
		return err
	}

	var buf bytes.Buffer
	buf.WriteString(`{"_comment":`)
	buf.Write(commentJSON)
	buf.WriteString(`,"kubernetes":`)
	buf.Write(kubernetesJSON)
	buf.WriteString(`,"sigs":`)
	buf.Write(sigsJSON)
	buf.WriteByte('}')

	return writeIndentedJSON(path, buf.Bytes())
}
