{ pkgs }:
pkgs.writeShellApplication {
  name = "generate-hashes";
  runtimeInputs = with pkgs; [
    gh
    jq
    nix-prefetch-github
  ];
  text = ''
    REPO_ROOT="$(git rev-parse --show-toplevel)"
    VERSIONS_JSON="$REPO_ROOT/versions.json"
    HASHES_JSON="$REPO_ROOT/hashes.json"
    TMPFILE="$(mktemp)"
    trap 'rm -f "$TMPFILE"' EXIT

    versions="$(cat "$VERSIONS_JSON")"
    hashes="$(cat "$HASHES_JSON" 2>/dev/null || echo '{}')"

    fetch_commit() {
      local owner="$1" repo="$2" tag="$3"
      local ref_data type sha
      ref_data="$(gh api "repos/$owner/$repo/git/refs/tags/$tag")"
      type="$(echo "$ref_data" | jq -r '.object.type')"
      sha="$(echo "$ref_data" | jq -r '.object.sha')"
      if [[ "$type" == "tag" ]]; then
        # Annotated tag: dereference to commit
        sha="$(gh api "repos/$owner/$repo/git/tags/$sha" | jq -r '.object.sha')"
      fi
      echo "$sha"
    }

    sig_owner() {
      case "$1" in
        cluster-api)        echo "kubernetes-sigs" ;;
        kube-state-metrics) echo "kubernetes" ;;
        metrics-server)     echo "kubernetes-sigs" ;;
        external-dns)       echo "kubernetes-sigs" ;;
        *) echo "Unknown SIG: $1" >&2; exit 1 ;;
      esac
    }

    # Process kubernetes core
    while IFS= read -r k8s_minor; do
      k8s_version="$(echo "$versions" | jq -r ".kubernetes.\"$k8s_minor\".version")"
      existing_version="$(echo "$hashes" | jq -r ".kubernetes.\"$k8s_minor\".version // empty")"
      existing_hash="$(echo "$hashes" | jq -r ".kubernetes.\"$k8s_minor\".srcHash // empty")"
      existing_commit="$(echo "$hashes" | jq -r ".kubernetes.\"$k8s_minor\".commit // empty")"

      if [[ "$existing_version" == "$k8s_version" && -n "$existing_hash" && -n "$existing_commit" ]]; then
        echo "kubernetes $k8s_minor ($k8s_version): cached" >&2
      else
        echo "kubernetes $k8s_minor ($k8s_version): fetching..." >&2
        src_hash="$(nix-prefetch-github --json --rev "v$k8s_version" kubernetes kubernetes | jq -r '.hash')"
        commit="$(fetch_commit kubernetes kubernetes "v$k8s_version")"
        hashes="$(echo "$hashes" | jq \
          ".kubernetes.\"$k8s_minor\" = {version: \"$k8s_version\", srcHash: \"$src_hash\", commit: \"$commit\"}")"
      fi
    done < <(echo "$versions" | jq -r '.supported[]')

    # Process SIGs
    while IFS= read -r k8s_minor; do
      for sig in cluster-api kube-state-metrics metrics-server external-dns; do
        sig_version="$(echo "$versions" | jq -r ".kubernetes.\"$k8s_minor\".sigs.\"$sig\"")"
        existing_version="$(echo "$hashes" | jq -r ".sigs.\"$sig\".\"$k8s_minor\".version // empty")"
        existing_hash="$(echo "$hashes" | jq -r ".sigs.\"$sig\".\"$k8s_minor\".hash // empty")"
        existing_commit="$(echo "$hashes" | jq -r ".sigs.\"$sig\".\"$k8s_minor\".commit // empty")"

        if [[ "$existing_version" == "$sig_version" && -n "$existing_hash" && -n "$existing_commit" ]]; then
          echo "  $sig $k8s_minor ($sig_version): cached" >&2
        else
          owner="$(sig_owner "$sig")"
          echo "  $sig $k8s_minor ($sig_version): fetching..." >&2
          sig_hash="$(nix-prefetch-github --json --rev "v$sig_version" "$owner" "$sig" | jq -r '.hash')"
          commit="$(fetch_commit "$owner" "$sig" "v$sig_version")"
          hashes="$(echo "$hashes" | jq \
            ".sigs.\"$sig\".\"$k8s_minor\" = {version: \"$sig_version\", hash: \"$sig_hash\", commit: \"$commit\"}")"
        fi
      done
    done < <(echo "$versions" | jq -r '.supported[]')

    echo "$hashes" | jq '{_comment: "Generated by make generate-hashes. Do not edit manually."} + .' > "$TMPFILE"
    mv "$TMPFILE" "$HASHES_JSON"
    echo "Wrote $HASHES_JSON" >&2
  '';
}
