{
  buildGoApplication,
  lib,
  mkGomod2nixUpdater,
  nix-update-script,
  version,
  src,
  modules,
}:
let
  updateGomod2nix = mkGomod2nixUpdater {
    inherit src;
    outdir = "core/${lib.versions.majorMinor version}";
  };
  mkBin =
    pname: subPkg: extraMeta:
    buildGoApplication {
      inherit
        pname
        version
        src
        modules
        ;

      subPackages = [ subPkg ];
      doCheck = false;
      ldflags = [
        "-w"
        "-s"
      ];

      # goConfigHook (postPatchHooks) replaces vendor/ with gomod2nix's module-mode
      # vendor, which has no "## workspace" header. k8s workspace builds expect
      # that header + staging module entries. We restore the source's own
      # vendor/modules.txt (workspace-mode, generated by go work vendor) so that
      # go accepts the vendor dir and resolves staging k8s.io/* from ./staging/.
      preConfigure = ''
        chmod u+w vendor
        cp ${src}/vendor/modules.txt vendor/modules.txt
      '';

      passthru = {
        updateScript = nix-update-script { };
        inherit updateGomod2nix;
      };

      meta =
        with lib;
        {
          homepage = "https://kubernetes.io";
          license = licenses.asl20;
          maintainers = with maintainers; [ UnstoppableMango ];
        }
        // extraMeta;
    };
in
{
  kubectl = mkBin "kubectl" "cmd/kubectl" {
    description = "Run commands against Kubernetes clusters";
    mainProgram = "kubectl";
  };
  kubeadm = mkBin "kubeadm" "cmd/kubeadm" {
    description = "Bootstrap a Kubernetes cluster";
    mainProgram = "kubeadm";
  };
  kubelet = mkBin "kubelet" "cmd/kubelet" {
    description = "Primary node agent for Kubernetes";
    mainProgram = "kubelet";
  };
  kube-apiserver = mkBin "kube-apiserver" "cmd/kube-apiserver" {
    description = "Kubernetes API server";
    mainProgram = "kube-apiserver";
  };
  kube-controller-manager = mkBin "kube-controller-manager" "cmd/kube-controller-manager" {
    description = "Kubernetes controller manager";
    mainProgram = "kube-controller-manager";
  };
  kube-scheduler = mkBin "kube-scheduler" "cmd/kube-scheduler" {
    description = "Kubernetes cluster scheduler";
    mainProgram = "kube-scheduler";
  };
  kube-proxy = mkBin "kube-proxy" "cmd/kube-proxy" {
    description = "Kubernetes network proxy";
    mainProgram = "kube-proxy";
  };
}
