{
  buildGoApplication,
  lib,
  mkGomod2nixUpdater,
  nix-update-script,
  version,
  src,
  modules,
}:
let
  updateGomod2nix = mkGomod2nixUpdater {
    inherit src;
    outdir = "core/${lib.versions.majorMinor version}";
  };

  # Mirrors hack/lib/version.sh kube::version::ldflags — injects version info
  # into both k8s.io/client-go/pkg/version and k8s.io/component-base/version.
  # gitCommit left empty and buildDate pinned to epoch for reproducibility.
  versionLdflags =
    let
      xFlag = pkg: key: val: "-X '${pkg}.${key}=${val}'";
      both = key: val: [
        (xFlag "k8s.io/client-go/pkg/version" key val)
        (xFlag "k8s.io/component-base/version" key val)
      ];
    in
    (both "gitVersion" "v${version}")
    ++ (both "gitMajor" (lib.versions.major version))
    ++ (both "gitMinor" (lib.versions.minor version))
    ++ (both "gitCommit" "")
    ++ (both "gitTreeState" "clean")
    ++ (both "buildDate" "1970-01-01T00:00:00Z");

  mkBin =
    pname: subPkg: static: extraMeta:
    buildGoApplication (
      {
        inherit
          pname
          version
          src
          modules
          ;

        subPackages = [ subPkg ];
        doCheck = false;
        ldflags =
          [
            "-w"
            "-s"
          ]
          ++ versionLdflags
          ++ lib.optionals static [
            "-extldflags '-static'"
            "-installsuffix static"
          ];

        # goConfigHook (postPatchHooks) replaces vendor/ with gomod2nix's module-mode
        # vendor, which has no "## workspace" header. k8s workspace builds expect
        # that header + staging module entries. We restore the source's own
        # vendor/modules.txt (workspace-mode, generated by go work vendor) so that
        # go accepts the vendor dir and resolves staging k8s.io/* from ./staging/.
        preConfigure = ''
          chmod u+w vendor
          cp ${src}/vendor/modules.txt vendor/modules.txt
        '';

        passthru = {
          updateScript = nix-update-script { };
          inherit updateGomod2nix;
        };

        meta =
          with lib;
          {
            homepage = "https://kubernetes.io";
            license = licenses.asl20;
            maintainers = with maintainers; [ UnstoppableMango ];
          }
          // extraMeta;
      }
      // lib.optionalAttrs static { CGO_ENABLED = 0; }
    );
in
{
  # kubectl is NOT in KUBE_STATIC_BINARIES — dynamically linked on Linux.
  kubectl = mkBin "kubectl" "cmd/kubectl" false {
    description = "Run commands against Kubernetes clusters";
    mainProgram = "kubectl";
  };
  # Remaining binaries are in KUBE_STATIC_BINARIES per hack/lib/golang.sh.
  kubeadm = mkBin "kubeadm" "cmd/kubeadm" true {
    description = "Bootstrap a Kubernetes cluster";
    mainProgram = "kubeadm";
  };
  kubelet = mkBin "kubelet" "cmd/kubelet" true {
    description = "Primary node agent for Kubernetes";
    mainProgram = "kubelet";
  };
  kube-apiserver = mkBin "kube-apiserver" "cmd/kube-apiserver" true {
    description = "Kubernetes API server";
    mainProgram = "kube-apiserver";
  };
  kube-controller-manager = mkBin "kube-controller-manager" "cmd/kube-controller-manager" true {
    description = "Kubernetes controller manager";
    mainProgram = "kube-controller-manager";
  };
  kube-scheduler = mkBin "kube-scheduler" "cmd/kube-scheduler" true {
    description = "Kubernetes cluster scheduler";
    mainProgram = "kube-scheduler";
  };
  kube-proxy = mkBin "kube-proxy" "cmd/kube-proxy" true {
    description = "Kubernetes network proxy";
    mainProgram = "kube-proxy";
  };
}
